standalone_tags:
  [
    {id: 0, size: 0.08, name: 'tag_1'},
    {id: 1, size: 0.08, name: 'tag_1'},
    {id: 2, size: 0.08, name: 'tag_2'},
    {id: 3, size: 0.08, name: 'tag_3'},
    {id: 4, size: 0.08, name: 'tag_4'},
    {id: 5, size: 0.08, name: 'tag_5'},
    {id: 6, size: 0.08, name: 'tag_6'},
    {id: 7, size: 0.08, name: 'tag_7'},
    {id: 8, size: 0.08, name: 'tag_8'},
    {id: 9, size: 0.08, name: 'tag_9'},
    {id: 10, size: 0.08, name: 'tag_10'},
    {id: 11, size: 0.08, name: 'tag_11'},
    {id: 12, size: 0.08, name: 'tag_12'},
    {id: 13, size: 0.08, name: 'tag_13'},
    {id: 14, size: 0.08, name: 'tag_14'},
    {id: 15, size: 0.08, name: 'tag_15'},
    {id: 16, size: 0.08, name: 'tag_16'},
    {id: 17, size: 0.08, name: 'tag_17'},
    {id: 18, size: 0.08, name: 'tag_18'},
    {id: 19, size: 0.08, name: 'tag_19'},
    {id: 20, size: 0.08, name: 'tag_20'}
  ]
tag_bundles:
  [
    # {
    #   name: 'my_bundle',
    #   layout:
    #     [
    #       {id: 0, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #       {id: 4, size: 0.05, x: 0.0548, y: -0.0522, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #       {id: 3, size: 0.05, x: -0.0580, y: -0.0553, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #       {id: 2, size: 0.05, x: 0.0543, y: 0.0603, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #       {id: 1, size: 0.05, x: -0.0582, y: 0.0573, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
    #     ]
    # }
  ]
